name: Deploy website
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          cd Calculator
          dotnet build
          git config user.name "Website Bot"
          git config user.email "no-reply@lotes-lab.de"
          git checkout -b website
          git add -f bin/Debug/net5.0/wwwroot
          git mv bin/Debug/net5.0/wwwroot/* ../*
          git mv wwwroot/* ../*
          git commit -am "Update website"
          git push --force origin website
      
          
