name: Deploy website
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          cd Calculator
          dotnet build
          git config user.name "Website Bot"
          git config user.email "no-reply@lotes-lab.de"
          git checkout -b website
          mv bin/Debug/net5.0/* ..
          mv ../wwwroot/* ..
          mv wwwroot/* ..
          git add --all
          git rm -r UnitTests Calculator .vs .github AntlrMeetsWebAssembly.sln
          git commit -am "Update website"
          git push --force origin website
      
          
